.!xgpcommands_";squish"

.font 1 "31vg";  font 2 "31vgi"; font 3 "31vgvb";font 4 "plunk";
.font 5 "fonts1;qrp kst"; font 6 "fonts;s25grk kst"; font 7 "20vg";

.turn on "" for "%"
.turn on  "_^[]&"

.margins(2125,2125,,)
.paper size(20000)


.tabbreak compact
.variable header, tagname;


.fill preface 1
.indent 4

.macro example begin nofill indent 0  turn off "^"
.millspacing_10 skip 1 select 3 

.MACRO SCON  SKIP 1 CONTINUE
.macro bcon  break continue 
.macro isolate (line)skip 1
line
.skip 1

.single space
foo bar
