(DEFUN TEST FEXPR (X)
(SET (CAR X) (CDR X)))

(DEFUN AV FEXPR (X)
(PRINT (CAR X))(PRINT (APPLY (QUOTE MAX) (CDR X)))(PRINT (APPLY (QUOTE MIN) 
(CDR X)))(PRINT (APPLY (QUOTE PLUS) (CDR X))))

(DEFUN FOO EXPR (X)
(DO ((PROP (GETL X (QUOTE (EXPR FEXPR MACRO))))) NIL (PRINC (QUOTE |(DEFUN |) 
SAVE-FILE) (PRIN1 X SAVE-FILE) (PRINC (QUOTE | |) SAVE-FILE) (PRIN1 (CAR 
PROP) SAVE-FILE) (PRINC (QUOTE | |) SAVE-FILE) (PRIN1 (CADADR PROP) 
SAVE-FILE) (TERPRI SAVE-FILE) (MAPCAR (QUOTE (LAMBDA (X) (PRIN1 X 
SAVE-FILE))) (CDDADR PROP)) (PRINC (QUOTE |)|) SAVE-FILE) (TERPRI SAVE-FILE) 
(TERPRI SAVE-FILE)))

(DEFUN AVERAGE FEXPR (X)
(PRINT (CAR X))(SET (CAR X) (CDR X))(PRINT (APPLY (QUOTE MAX) (CDR X)))
(PRINT (APPLY (QUOTE MIN) (CDR X)))(FIX (PLUS 0.5 (QUOTIENT (APPLY (QUOTE 
PLUS) (CDR X)) (FLOAT (LENGTH (CDR X)))))))

(DEFUN SAVE EXPR NIL
(DO ((SAVE-FILE (OPEN (LIST (QUOTE (DSK TEACH)) (STATUS UNAME) (QUOTE HACK)) 
(QUOTE OUT)))) NIL (MAPATOMS (QUOTE (LAMBDA (X) (COND ((GETL X (QUOTE (EXPR 
FEXPR))) (FOO X)))))) (CLOSE SAVE-FILE)))

