(DEFUN WHOJ EXPR NIL
(DO ((READTABLE (GET (ARRAY NEWREADTABLE READTABLE) (QUOTE ARRAY)))) (TTY*) 
(WHO) (WHOLIST) (UR (CRUNIT)) (TTY-FILE ((LAMBDA (TTY-FILE) (READ TTY-FILE) 
(READ TTY-FILE) (READ TTY-FILE) TTY-FILE) (OPEN (QUOTE ((TTY) |.file.| 
|(dir)|)) (QUOTE SINGLE))))) ((EQ TTY* (QUOTE FREE)) (CLOSE TTY-FILE) (APPLY 
(QUOTE CRUNIT) UR) WHOLIST) (READ TTY-FILE) (READ TTY-FILE) (SETQ TTY* 
(READLIST (CDDR (EXPLODEC (READ TTY-FILE))))) (COND ((OR (EQ TTY* (QUOTE 
DSN)) (EQ TTY* (QUOTE FREE)))) (T (SETQ WHOLIST (CONS (LIST (READUNAME) 
(READ TTY-FILE)) WHOLIST))))))

(DEFUN LIST-LISP-FUNCTIONS EXPR NIL
(MAPATOMS (QUOTE FUNC-PRINT)))

(DEFUN FOO EXPR (X)
(DO ((PROP (GETL X (QUOTE (EXPR FEXPR MACRO))))) NIL (PRINC (QUOTE |(DEFUN |) 
SAVE-FILE) (PRIN1 X SAVE-FILE) (PRINC (QUOTE | |) SAVE-FILE) (PRIN1 (CAR 
PROP) SAVE-FILE) (PRINC (QUOTE | |) SAVE-FILE) (PRIN1 (CADADR PROP) 
SAVE-FILE) (TERPRI SAVE-FILE) (MAPCAR (QUOTE (LAMBDA (X) (PRIN1 X 
SAVE-FILE))) (CDDADR PROP)) (PRINC (QUOTE |)|) SAVE-FILE) (TERPRI SAVE-FILE) 
(TERPRI SAVE-FILE)))

(DEFUN WHO EXPR NIL
(MAPCAR (QUOTE CAR) (WHOJ)))

(DEFUN /` EXPR (X)
(COND ((ATOM X) (LIST (QUOTE QUOTE) X)) ((EQ (QUOTE |,|) (CAR X)) (CADR X)) 
(T (LIST (QUOTE CONS) (/` (CAR X)) (/` (CDR X))))))

(DEFUN READUNAME EXPR NIL
(TYI TTY-FILE)(DO ((I 1 (1+ I)) (L) (N)) ((> I 6) (IMPLODE (NREVERSE L))) 
(SETQ N (TYI TTY-FILE)) (OR (= N 32) (SETQ L (CONS N L)))))

(DEFUN LUSER EXPR ARGLIST
(PROG (LIST) (COND ((OR (= ARGLIST 0) (= ARGLIST 1)) (SETQ LIST (QUOTE (RWK 
KMP KGK ELLEN NEAL)))) (T (SETQ LIST (ARG 2)))) (COND ((= ARGLIST 1) (SETQ 
SUBJ (ARG 1))) ((= ARGLIST 2) (SETQ SUBJ (ARG 1))) (T (SETQ SUBJ (QUOTE 
LISP)))) (COND ((MEMBER (CAR LIST) (WHO)) (SETQ FILE (OPEN (LIST (QUOTE 
(CLI)) (CAR LIST) (QUOTE HACTRN)) (QUOTE (ASCII OUT)))) (PRINC (ASCII 127) 
FILE) (PRINC (QUOTE |[Message from |) FILE) (PRINC (STATUS UNAME) FILE) 
(PRINC (QUOTE |]/
Excuse me, |) FILE) (PRINC (CAR LIST) FILE) (PRINC (QUOTE 
|, could I please have some help with |) FILE) (PRINC SUBJ FILE) (PRINC 
(QUOTE ?) FILE) (PRINC (ASCII 13) FILE) (PRINC (ASCII 10) FILE) (CLOSE FILE) 
(PRINC (QUOTE |/
Asking |)) (PRINC (CAR LIST)) (PRINC (QUOTE | for help../
|)) (RETURN (QUOTE *))) ((NULL LIST) (RETURN (QUOTE 
|Sorry, there's noone here to help you./
|))) (T (LUSER SUBJ (CDR LIST))))))

(DEFUN FUNC-PRINT EXPR (X)
(COND ((GETL X (QUOTE (FEXPR EXPR LEXPR))) (PRINC (ASCII 13)) (PRINC (ASCII 
10)) (PRINC X) (PRINC (ASCII 9)) (PRINC (CAR (GETL X (QUOTE (FEXPR EXPR 
LEXPR))))) (PRINC (QUOTE ?)) (SETQ OPT (READCH)) (AND (EQUAL OPT (QUOTE Y)) 
(PRINC (CDR (GETL X (QUOTE (FEXPR EXPR LEXPR)))))))))

(DEFUN SAVE EXPR NIL
(DO ((SAVE-FILE (OPEN (LIST (QUOTE (DSK ARMTE)) (QUOTE STVLSP) (QUOTE >)) 
(QUOTE OUT)))) NIL (MAPATOMS (QUOTE (LAMBDA (X) (COND ((GETL X (QUOTE (EXPR 
FEXPR))) (FOO X)))))) (CLOSE SAVE-FILE)))

(defun replace-all (var1 var2 list)
       (cond ((atom list) list)
	     ((equal var1 (car list)) (cons var2 (replace-all
					     var1 var2 (cdr list))))
	     (t (cons (replace-all var1 var2 (car list))
		      (replace-all var1 var2 (cdr list))))

	     ))